### ISSUE TITLE
There doesn't seem to be any documentation on how to use this tool.

### ISSUE THREAD

**Issue by calicorabbit** [asaf-b/mnsAnnotate#2]
I have looked all over and cannot find any instructions on the basics of how to use this. I am not sure where I go to add it, or if there is a UI for it, or really anything

**Comment by asaf-b** [comment]
Hi calicorabbit,
There is a UI within the full Mansur-Rig product- you can use the Dynamic-UI-Creator tool within Mansur-Rig to launch a UI.
Although using this node is extremely simple- you simply create the node in the node editor and connect the attributes you want to be displayed. Once you connect the attributes they will be annotated in the viewport.
Here is the documentation of the node's attributes: https://docs.mansur-rig.com/Maya-Plugins/#mnsannotate
You need to connect your attributes to the node's "attributes" array attribute.
