### ISSUE TITLE
Please add String support

### ISSUE THREAD

**Issue by NeoReel** [asaf-b/mnsAnnotate#3]
Not sure if there is still dev made on this, but is there any way to add String support?
At this time, it only takes in numerical values, but it would be nice to have a single input string attribute.
So, as an example, instead of using the node's name, you could have a string prefix. (doesn;t have to be a prefix, I would personally use it just to show that string)

Please let me know if this is possible...
Otherwise, maybe I can have the source?

Thanks a lot!

**Comment by asaf-b** [comment]
Hi there
mnsAnnotate doesn't support string attributes, but it does support enum attributes.
I'm not sure what is the goal of what you are trying to do, but basically creating an enum with the string you are looking for as one of the enums should be a sufficient workaround.

Best,
Asaf

**Comment by NeoReel** [comment]
Aah, too bad! I'll give a try to enums, though it is not dynamic enough for my needs.

Basically, I just want to write some comment text to screen using your plugin. So for instance, I'd like to burn in the name of the file into the playblast. I'd also like to add a comment by the animator, such as  "First Draft" or more elaborate, like "This is a first draft of the anim, color fixed.".

If it would be a string attribute, it would work best.
Right now, the only thing I was able to do was to rename the object to "First_Draft" which would output correctly when using the node name option. This doesn't work when the node is referenced, so I have to fiddle too much. It also doesn't support punctuation using a node name.

**Comment by asaf-b** [comment]
Sorry. But I think there is an easy way to create a custom annotation (heads-up display in Maya 2022)
Have you tried this? 
https://knowledge.autodesk.com/support/maya/learn-explore/caas/CloudHelp/cloudhelp/2022/ENU/Maya-Customizing/files/GUID-5C6AFD87-82DE-4C4B-B3F1-DB4A0C3B59C4-htm.html

**Comment by NeoReel** [comment]
Yes, I know about the annotation node. That is actually what I'm currently using, but the size of the font is not changeable, so in a FullHD playblast, the annotation is minuscule. Thus the reason why I wanted to use your plugin.
It's all good, I'm not stuck in any way, I wanted my annotations to be bigger, thats all! :-)
Take care!
